In [119]:
import torch
import torch.nn as nn
import torch.optim as optim


In [ ]:
a = torch.arange(16)
b = a.reshape(2, 2, 4)
c = torch.arange(15, -1, -1)
d = c.reshape(2, 2, 4)
d.sum(dim = 1)
#广播,维度相同,先拓展复制再计算
a

torch.Size([2, 4])

In [30]:
 #张量转标量
t = torch.randn(1)
t.item()

0.9456992149353027

In [59]:
#自动求导
x = torch.randn(size = (3, 3), requires_grad = True)
print(x)
x.requires_grad_(True)
x.grad

y = 2 * (x @ x).sum()
y

tensor([[-0.1180,  0.5785,  0.8382],
        [ 0.7039,  0.8423,  0.9306],
        [ 0.3605,  0.6687, -0.6849]], requires_grad=True)


tensor(13.5557, grad_fn=<MulBackward0>)

In [60]:
y.backward()
x.grad

tensor([[4.4902, 6.8465, 2.5815],
        [6.7765, 9.1328, 4.8678],
        [4.7652, 7.1216, 2.8566]])

In [61]:
x.grad.zero_()
y = (x * x).sum()
y

tensor(4.1684, grad_fn=<SumBackward0>)

In [62]:
y.backward()
x.grad

tensor([[-0.2360,  1.1570,  1.6764],
        [ 1.4078,  1.6847,  1.8613],
        [ 0.7211,  1.3374, -1.3698]])

In [63]:
x.grad.zero_()
y = x*x*x
u = y.sin().sum()
u

tensor(2.3978, grad_fn=<SumBackward0>)

In [64]:
u.backward()
x.grad

tensor([[0.0418, 0.9852, 1.7527],
        [1.3969, 1.7596, 1.7990],
        [0.3895, 1.2820, 1.3352]])

In [139]:
def forward():
    y_v = w * x + b
    return y_v
    

x = torch.arange(16).reshape(4, 4)/15
y_t = 2 * x + 1
w = torch.tensor([1.], requires_grad= True)
b = torch.tensor([0.], requires_grad= True)
nn.Linear(1,1)
lr = 0.5
for epoch in range(500):
    if epoch != 0:
        w.grad.zero_()
        b.grad.zero_()
    y_v = forward()
    loss = ((y_v - y_t)**2).sum()/32
    loss.backward()
    with torch.no_grad():
        w -= w.grad * lr
        b -= b.grad * lr
print(f'w: {w.detach().item(): .4f}\nb: {b.detach().item(): .4f}')


w:  2.0000
b:  1.0000
